# Generated by Django 4.2.2 on 2023-06-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_is_active_alter_appuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_active',
        ),
    ]
